#!/bin/bash

# LightRAG Automatic Installation Script
# This script installs LightRAG, LightRAG Server, and WebUI with LM Studio support

set -e  # Exit on any error

# --- Configuration ---
PROJECT_DIR="/Users/drp/Proyectos/LR1"
LM_STUDIO_HOST="http://localhost:1234"
LLM_MODEL_NAME="your-llm-model-name"  # Replace with your actual model name loaded in LM Studio
EMBEDDING_MODEL_NAME="nomic-embed-text"
RERANKER_MODEL_NAME="BAAI/bge-reranker-v2-m3"  # Example reranker model

# --- Colors for output ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}Starting LightRAG installation...${NC}"

# --- 1. Create Project Directory ---
echo -e "${YELLOW}Creating project directory at ${PROJECT_DIR}...${NC}"
mkdir -p "$PROJECT_DIR"
cd "$PROJECT_DIR"

# --- 2. Set up Python Virtual Environment ---
echo -e "${YELLOW}Setting up Python virtual environment...${NC}"
if [ ! -d ".venv" ]; then
    python3 -m venv .venv
fi
source .venv/bin/activate

# --- 3. Install LightRAG and Dependencies ---
echo -e "${YELLOW}Installing LightRAG and its dependencies...${NC}"

# Install uv for faster dependency management (recommended by LightRAG)
if ! command -v uv &> /dev/null; then
    echo "Installing uv..."
    curl -LsSf https://astral.sh/uv/install.sh | sh
    source "$HOME/.cargo/env"  # Source cargo environment for uv
fi

# Clone the LightRAG repository if it doesn't exist
if [ ! -d "LightRAG" ]; then
    git clone https://github.com/HKUDS/LightRAG.git
fi

cd LightRAG

# Sync the environment with uv (creates .venv inside the project)
echo -e "${YELLOW}Syncing dependencies with uv...${NC}"
uv sync --extra api

# Activate the virtual environment created by uv
source .venv/bin/activate

# Build front-end artifacts for the WebUI
echo -e "${YELLOW}Building LightRAG Web UI...${NC}"
cd lightrag_webui
bun install --frozen-lockfile || { echo -e "${RED}Failed to install bun dependencies. Please install bun first.${NC}"; exit 1; }
bun run build || { echo -e "${RED}Failed to build the Web UI.${NC}"; exit 1; }
cd ..

# --- 4. Configure Environment ---
echo -e "${YELLOW}Configuring environment variables...${NC}"

# Create .env file from the example
if [ ! -f ".env" ]; then
    cp env.example .env
fi

# Update the .env file with user-specific configurations using sed
# Note: sed -i '' is used for macOS compatibility

# LLM Configuration (for LM Studio)
sed -i '' "s|^LLM_BINDING=.*|LLM_BINDING=openai|" .env
sed -i '' "s|^LLM_MODEL=.*|LLM_MODEL=${LLM_MODEL_NAME}|" .env
sed -i '' "s|^LLM_BINDING_HOST=.*|LLM_BINDING_HOST=${LM_STUDIO_HOST}/v1|" .env
sed -i '' "s|^LLM_BINDING_API_KEY=.*|LLM_BINDING_API_KEY=lm-studio|" .env

# Embedding Configuration (for LM Studio)
sed -i '' "s|^EMBEDDING_BINDING=.*|EMBEDDING_BINDING=openai|" .env
sed -i '' "s|^EMBEDDING_MODEL=.*|EMBEDDING_MODEL=${EMBEDDING_MODEL_NAME}|" .env
sed -i '' "s|^EMBEDDING_DIM=.*|EMBEDDING_DIM=768|" .env  # nomic-embed-text typically uses 768 dimensions
sed -i '' "s|^EMBEDDING_SEND_DIM=.*|EMBEDDING_SEND_DIM=false|" .env
sed -i '' "s|^EMBEDDING_TOKEN_LIMIT=.*|EMBEDDING_TOKEN_LIMIT=8192|" .env
sed -i '' "s|^EMBEDDING_BINDING_HOST=.*|EMBEDDING_BINDING_HOST=${LM_STUDIO_HOST}/v1|" .env
sed -i '' "s|^EMBEDDING_BINDING_API_KEY=.*|EMBEDDING_BINDING_API_KEY=lm-studio|" .env

# Reranker Configuration (for LM Studio)
sed -i '' "s|^RERANK_BINDING=.*|RERANK_BINDING=openai|" .env
sed -i '' "s|^RERANK_MODEL=.*|RERANK_MODEL=${RERANKER_MODEL_NAME}|" .env
sed -i '' "s|^RERANK_BINDING_HOST=.*|RERANK_BINDING_HOST=${LM_STUDIO_HOST}/v1/rerank|" .env
sed -i '' "s|^RERANK_BINDING_API_KEY=.*|RERANK_BINDING_API_KEY=lm-studio|" .env

# Server Configuration
sed -i '' "s|^HOST=.*|HOST=0.0.0.0|" .env
sed -i '' "s|^PORT=.*|PORT=9621|" .env

# Directory Configuration
sed -i '' "s|^# INPUT_DIR=.*|INPUT_DIR=${PROJECT_DIR}/LightRAG/inputs|" .env
sed -i '' "s|^# WORKING_DIR=.*|WORKING_DIR=${PROJECT_DIR}/LightRAG/rag_storage|" .env

# Enable Reranker by default
sed -i '' "s|^# RERANK_BY_DEFAULT=.*|RERANK_BY_DEFAULT=True|" .env

echo -e "${GREEN}Environment configuration complete.${NC}"

# --- 5. Create Configuration File ---
echo -e "${YELLOW}Creating configuration file with all keys and addresses...${NC}"

CONFIG_FILE="${PROJECT_DIR}/lightrag_config.env"
cat > "$CONFIG_FILE" << EOF
# LightRAG Configuration File
# Generated by install_lightrag.sh

# Project Directory
PROJECT_DIR=${PROJECT_DIR}

# LM Studio Connection
LM_STUDIO_HOST=${LM_STUDIO_HOST}
LLM_MODEL_NAME=${LLM_MODEL_NAME}
EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME}
RERANKER_MODEL_NAME=${RERANKER_MODEL_NAME}

# LightRAG Server Details
SERVER_HOST=0.0.0.0
SERVER_PORT=9621
WEBUI_URL=http://localhost:9621

# Storage Paths
INPUT_DIR=${PROJECT_DIR}/LightRAG/inputs
WORKING_DIR=${PROJECT_DIR}/LightRAG/rag_storage

# API Key for Server Access
LIGHTRAG_API_KEY=your-secure-api-key-here

# Model-Specific Settings
OLLAMA_LLM_NUM_CTX=32768
EOF

echo -e "${GREEN}Configuration file created at ${CONFIG_FILE}${NC}"

# --- 6. Finalize and Provide Instructions ---
echo -e "${GREEN}Installation complete!${NC}"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo "1. Ensure LM Studio is running and the models (${LLM_MODEL_NAME}, ${EMBEDDING_MODEL_NAME}) are loaded."
echo "2. Start the LightRAG server:"
echo "   cd ${PROJECT_DIR}/LightRAG"
echo "   source .venv/bin/activate"
echo "   lightrag-server"
echo ""
echo -e "${YELLOW}Configuration file location:${NC}"
echo "   ${CONFIG_FILE}"
echo ""
echo -e "${YELLOW}Web UI will be available at:${NC}"
echo "   http://localhost:9621"